### ISSUE TITLE
Installation on K3d

### ISSUE THREAD

**Issue by rupipal** [liqotech/liqo#1028] opened 2021-12-16 18:21 UTC
Hi,
I'm trying to install liqo on a K3d cluster ( https://github.com/rancher/k3d  https://www.suse.com/c/introduction-k3d-run-k3s-docker-src/ ). I found the following issues. Could somebody help? What is the command/utilty for K3d?

With

$liqoctl install k3s --generate-name ( or -n <name> )

* Initializing installer... 🔌 
* Retrieving cluster configuration from cluster provider... 📜  
A random cluster name was generated for you: empty-wildflower
* Installing or Upgrading Liqo... (this may take few minutes) ⏳ 
E1216 23:27:11.161612   24695 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1216 23:27:11.201929   24695 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1216 23:27:11.209676   24695 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1216 23:27:11.210944   24695 memcache.go:196] continuing
E1216 23:27:11.212832   24695 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1216 23:27:11.220912   24695 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request

...
Error: timed out waiting for the condition

I simply gave the command a try,

$liqoctl install kind --generate-name 

* Initializing installer... 🔌 
* Retrieving cluster configuration from cluster provider... 📜  
A random cluster name was generated for you: wispy-frog
Error: kube-controller-manager not found

**Comment by frisso** [comment] 2021-12-18 11:37
@rupipal, supporting all the platforms all around may be difficult for our team. We never tested K3s on Docker.
Did you have any chance to install K3s either on the bare metal or on a VM and try if this works?

**Comment by rupipal** [comment] 2021-12-18 18:15
Hi Fuvio,
I haven't tried the other K3s install options as yet. Liqo seems to have
been tested  on K3s and I'm sure I wouldn't ordinarily have any issue if I
have a K3s installation. I've already checked out kind quickstarts. My
immediate interest in K3s ( and hence K3d) arose because of its potential
for edge clusters, Thus, K3d is a convenient sanbox to check some other
edge cluster softwares (  https://github.com/project-akri/akri
https://github.com/project-akri/akri-on-krustlet ). And that is where I'm
looking at possibilities with Liqo as to how it can integrate.

Rupinder

**Comment by frisso** [comment] 2021-12-19 08:12
@rupipal The problem is that Liqo needs a to acquire lot of parameters from the running cluster in order to properly setup the environment. The scraping of the above parameter is done by `liqoctl`, which has been customized for each one of the supported environment (K3s, K8s, Openshitf, etc). So, for instance, starting `liqoctl` in _K3s_ may be different than starting liqoctl in _K3s-in-Docker_. That would be the reason your installation fails. And, given the current resources of the team, we cannot support all the possible environments and we gave the precedence to more common setups.
Therefore we kindly ask you to install K3s on a vanilla VM; this is a supported platform, hence it should work.

**Comment by rupipal** [comment] 2021-12-19 08:50
Thanks Fulvio. Will try it as required.

**Comment by aleoli** [comment] 2022-02-04 10:20
Hi @rupipal! I tested the installation of the current release (v0.3.2) with `liqoctl install k3s --generate-name` on k3d and it seems to work correctly. Closing this issue, feel free to reopen it if needed.

**Closed by aleoli** 2022-02-04 10:20 UTC
Labels: kind/bug

**Comment by rupipal** [comment] 2022-02-04 11:51
Hi @aleoli 

Thanks. It works. I think the initial error codes I reported were harmless.

I tested with two K3d clusters. However, the auto-discovery of foreign clusters (auto peering) doesn't work. I tried peering commands; those didn't work either. I  get Error and not established.

kubectl get foreignclusters
NAME           OUTGOING PEERING PHASE   INCOMING PEERING PHASE   NETWORKING STATUS   AUTHENTICATION STATUS   AGE
ancient-lake                                                                         Error                   18m

**Comment by frisso** [comment] 2022-02-04 11:53
@aleoli Maybe opening a more specific issue?

**Comment by aleoli** [comment] 2022-02-04 13:39
Ref. #1090

**Comment by rupipal** [comment] 2022-02-04 13:44
Thanks. Will look it up and track it.
