### ISSUE TITLE
Unable to peer k3s and azure aks

### ISSUE THREAD

**Issue by AccHimanshu** [liqotech/liqo#1435] opened 2022-09-13 10:26 UTC
1. When we are using peering command virtual node is not getting created on either one of them.

2. $ kubectl get nodes liqo-d272662b-9e13-4f7d-a2e7-a15bb70ff0aa
Error from server (NotFound): nodes "liqo-d272662b-9e13-4f7d-a2e7-a15bb70ff0aa" not found

3. $ kubectl get nodes liqo-356cef35-fd29-46b4-9c40-3074901fd877
Error from server (NotFound): nodes "liqo-356cef35-fd29-46b4-9c40-3074901fd877" not found

**Comment by giorio94** [comment] 2022-09-13 10:43
Hi @AccHimanshu,

Could you please provide more details about your issue? Which is your configuration? What commands did you issue? What would you expect to occur and did not happen? Please, post also any logs that might be relevant to help you troubleshooting the problem.

By the way, in recent versions liqo nodes are no longer named after the cluster ID, but they reflect the mnemonic cluster name.

**Comment by AccHimanshu** [comment] 2022-09-13 11:18
I am using version 4 of the liqo both on k3s and aks system. Then running the peering command which comes as output of the liqo installation.

**Comment by giorio94** [comment] 2022-09-13 12:46
As mentioned in other threads, we do strongly suggest using liqo v0.5, as it includes different fixes for already identified bugs. liqoctl is also more user friendly, providing better feedback whether a given operation succeeded or not.

That said, when running the command, are you experiencing any error? Are the foreigncluster resources created on both clusters? Which is their status?

Could you also please post the logs of the liqo pods?

**Comment by AccHimanshu** [comment] 2022-09-16 06:58
Liqoctl command generated on k3s cluster -

liqoctl add cluster default --auth-url https://172.16.**.**:31572 --id 356cef35-fd29-46b4-9c40-3074901fd877 --token c6dc2ec470102307cc8d1e387d8050c547ad2aede4e27fbbff381b8d825524ba1ad1de59be06cd8033d229f2d19e20b092357c017c86bf8bd158d722b70d3611

In auth url it is showing private IP. Is this the reason for not getting peered

**Comment by giorio94** [comment] 2022-09-16 09:46
Yes, the authentication URL must be reachable from the other cluster. This is likely the cause of your issue.

In case you have only one cluster with public IPs (i.e., the one on Azure), you shall use the in-band peering approach: https://docs.liqo.io/en/v0.5.4/usage/peer.html#in-band-control-plane. This is supported on Liqo v0.5 only though.

**Comment by giorio94** [comment] 2022-09-28 07:08
Closing, as this does not appear to be an issue of Liqo, but rather connectivity problems between the clusters.

**Closed by giorio94** 2022-09-28 07:08 UTC
Labels: kind/bug
